name: nlp-course-small
channels:
  - conda-forge
  - anaconda
  - jim-hart
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.3=pyhd8ed1ab_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bs4=4.9.3=0
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py38haa244fe_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - freetype=2.10.4=h546665d_1
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py38hc5df569_1
  - ipython=7.22.0=py38h43734a8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38haa244fe_2
  - jpeg=9b=vc14h4d7706e_1
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38haa244fe_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libiconv=1.15=vc14h29686d3_5
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.1.0=h56a325e_1
  - libxml2=2.9.10=h5d81f1c_2
  - libxslt=1.1.33=h65864e5_2
  - lxml=4.6.3=py38h292cb97_0
  - lz4-c=1.9.3=h8ffe710_0
  - mkl=2020.4=hb70f87d_311
  - numpy=1.20.2=py38h09042cb_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h8ffe710_0
  - pandas=1.2.3=py38h4c96930_0
  - parso=0.8.1=pyhd8ed1ab_0
  - pdfminer=20191125=pyhd8ed1ab_1
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.0=py38hca74424_0
  - pip=21.0.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - pycryptodome=3.10.1=py38h294d835_0
  - pygments=2.8.1=pyhd8ed1ab_0
  - pypdf2=1.26.0=py_2
  - pytesseract=0.3.7=pyhd3deb0d_0
  - python=3.8.8=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=300=py38h294d835_0
  - pyzmq=22.0.3=py38h09162b1_1
  - setuptools=49.6.0=py38haa244fe_3
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.35.3=h8ffe710_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py38h294d835_1
  - traitlets=5.0.5=py_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - wincertstore=0.2=py38haa244fe_1006
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.4=ha9fde0e_3
  - pip:
    - python-docx==0.8.10
    - python-pptx==0.6.18
    - xlsxwriter==1.3.7
prefix: C:\Users\adoanvo\Anaconda3\envs\nlp-course-small
